Use Debian package maintainer script systemd fragments from Debian dh_installsystemd autoscripts instead of home-grown commands.

diff --git a/debian/scripts/postinst b/debian/scripts/postinst
--- a/debian/scripts/postinst
+++ b/debian/scripts/postinst
@@ -36,9 +36,32 @@ create_first_time_configuration() {
     fi
 }
 
+# See: https://salsa.debian.org/debian/debhelper/-/blob/debian/13.1/autoscripts/postinst-systemd-dont-enable
+# This is what dh_installsystemd would add but Cargo Deb doesn't use debhelper
+# so we have to add it ourselves manually.
+manage_systemd() {
+    if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+        if deb-systemd-helper debian-installed 'krill.service'; then
+            # This will only remove masks created by d-s-h on package removal.
+            deb-systemd-helper unmask 'krill.service' >/dev/null || true
+    
+            if deb-systemd-helper --quiet was-enabled 'krill.service'; then
+                # Create new symlinks, if any.
+                deb-systemd-helper enable 'krill.service' >/dev/null || true
+            fi
+        fi
+    
+        # Update the statefile to add new symlinks (if any), which need to be cleaned
+        # up on purge. Also remove old symlinks.
+        deb-systemd-helper update-state 'krill.service' >/dev/null || true
+    fi
+}
+
 case "$1" in
 configure)
     create_user
     create_first_time_configuration
     ;;
 esac
+
+manage_systemd $1
