Quick hack to try and use Rocky Linux in place of CentOS 8 due to timeouts to the Centos 8 vault package repo.

diff --git a/.github/workflows/pkg.yml b/.github/workflows/pkg.yml
--- a/.github/workflows/pkg.yml
+++ b/.github/workflows/pkg.yml
@@ -54,10 +54,12 @@ jobs:
           - 'debian:buster'   # debian/10
           - 'debian:bullseye' # debian/11
           - 'centos:7'
-          - 'centos:8'
+          - 'rockylinux:8'    # compatible with EOL centos:8
         include:
           - image: 'centos:7'
             extra_build_args: '--features static-openssl'
+          - image: 'rockylinux:8'
+            os: 'centos:8'
     env:
       CARGO_DEB_VER: 1.34.2
       CARGO_GENERATE_RPM_VER: 0.6.0
@@ -77,21 +79,19 @@ jobs:
       run: |
         # Get the operating system and release name (e.g. ubuntu and xenial) from the image name (e.g. ubuntu:xenial) by
         # extracting only the parts before and after but not including the colon:
-        echo "OS_NAME=${MATRIX_IMAGE%:*}" >> $GITHUB_ENV
-        echo "OS_REL=${MATRIX_IMAGE#*:}" >> $GITHUB_ENV
+        IMAGE="${MATRIX_IMAGE}"
+        if [ "${MATRIX_OS}" != "" ]; then
+          IMAGE="${MATRIX_OS}"
+        fi
+        echo "OS_NAME=${IMAGE%:*}" >> $GITHUB_ENV
+        echo "OS_REL=${IMAGE#*:}" >> $GITHUB_ENV
       env:
         MATRIX_IMAGE: ${{ matrix.image }}
+        MATRIX_OS: ${{ matrix.os }}
 
     # Git clone the Krill code in the branch we were invoked on.
     - name: Checkout repository
       uses: actions/checkout@v2
-
-    # Allow CentOS 8 to continue working now that it is EOL
-    # See: https://stackoverflow.com/a/70930049
-    - name: CentOS 8 EOL workaround
-      if: matrix.image == 'centos:8'
-      run: |
-        sed -i -e 's|mirrorlist=|#mirrorlist=|g' -e 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
 
     # Install Rust the hard way rather than using a GH Action because the action doesn't work inside a Docker container.
     - name: Install Rust
@@ -187,7 +187,6 @@ jobs:
     - name: Create the package
       env:
         MATRIX_PKG: ${{ matrix.pkg }}
-        MATRIX_IMAGE: ${{ matrix.image }}
         EXTRA_BUILD_ARGS: ${{ matrix.extra_build_args }}
       run: |
         # Debian
@@ -265,7 +264,7 @@ jobs:
             sed -i -e "s/$KRILL_VER/$PKG_KRILL_VER/" Cargo.toml
 
             # Select the correct systemd service unit file for the target operating system
-            case ${MATRIX_IMAGE} in
+            case "${OS_NAME}:${OS_REL}" in
               centos:7)
                 SYSTEMD_SERVICE_UNIT_FILE="krill-ubuntu-xenial.krill.service"
                 # yum install fails on older CentOS with the default LZMA compression used by cargo generate-rpm since v0.5.0
@@ -277,21 +276,17 @@ jobs:
                 EXTRA_CARGO_GENERATE_RPM_ARGS=""
                 ;;
               *)
-                echo >&2 "ERROR: Unsupported matrix image value: '${MATRIX_IMAGE}'"
+                echo >&2 "ERROR: Unsupported matrix image value: '${OS_NAME}:${OS_REL}'"
                 ;;
             esac
 
             case ${MATRIX_PKG} in
               krill)
                 # Select the correct systemd service unit file for the target operating system
-                case ${MATRIX_IMAGE} in
-                  ubuntu:xenial|centos:7)   SYSTEMD_SERVICE_UNIT_FILE="krill-ubuntu-xenial.krill.service"   ;;
-                  ubuntu:bionic)            SYSTEMD_SERVICE_UNIT_FILE="krill-ubuntu-bionic.krill.service"   ;;
-                  ubuntu:focal|centos:8)    SYSTEMD_SERVICE_UNIT_FILE="krill-ubuntu-focal.krill.service"    ;;
-                  debian:stretch)           SYSTEMD_SERVICE_UNIT_FILE="krill-debian-stretch.krill.service"  ;;
-                  debian:buster)            SYSTEMD_SERVICE_UNIT_FILE="krill-debian-buster.krill.service"   ;;
-                  debian:bullseye)          SYSTEMD_SERVICE_UNIT_FILE="krill-debian-bullseye.krill.service" ;;
-                  *) echo >&2 "ERROR: Unsupported matrix image value: '${MATRIX_IMAGE}'" ;;
+                case "${OS_NAME}:${OS_REL}" in
+                  centos:7) SYSTEMD_SERVICE_UNIT_FILE="krill-ubuntu-xenial.krill.service"   ;;
+                  centos:8) SYSTEMD_SERVICE_UNIT_FILE="krill-ubuntu-focal.krill.service"    ;;
+                  *) echo >&2 "ERROR: Unsupported matrix image value: '${OS_NAME}:${OS_REL}'" ;;
                 esac
 
                 # Copy the chosen systemd service unit file to where Cargo.toml expects it to be
@@ -474,11 +469,6 @@ jobs:
             sg lxd -c "lxc exec testcon -- apt-get install -y -o Dpkg::Options::=\"--force-confnew\" apt-transport-https ca-certificates man sudo wget"
             ;;
           centos)
-            if [[ "${MATRIX_IMAGE}" == "centos:8" ]]; then
-              # allow CentOS 8 to continue working now that it is EOL
-              # see: https://stackoverflow.com/a/70930049
-              sg lxd -c "lxc exec testcon -- sed -i -e 's|mirrorlist=|#mirrorlist=|g' -e 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*"
-            fi
             sg lxd -c "lxc exec testcon -- yum update -y"
             sg lxd -c "lxc exec testcon -- yum install -y man"
             ;;
