Bump cargo-deb and cargo-generate-rpm. (#758)

diff --git a/.github/workflows/pkg.yml b/.github/workflows/pkg.yml
--- a/.github/workflows/pkg.yml
+++ b/.github/workflows/pkg.yml
@@ -66,8 +66,8 @@ jobs:
           - image: 'centos:7'
             extra_build_args: '--features static-openssl'
     env:
-      CARGO_DEB_VER: 1.28.0
-      CARGO_GENERATE_RPM_VER: 0.4.0
+      CARGO_DEB_VER: 1.34.2
+      CARGO_GENERATE_RPM_VER: 0.6.0
       # A Krill version of the form 'x.y.z-bis' denotes a dev build that is newer than the released x.y.z version but is
       # not yet a new release.
       NEXT_VER_LABEL: bis
@@ -159,7 +159,17 @@ jobs:
       run: |
         case ${OS_NAME} in
           debian|ubuntu)
-            cargo install cargo-deb --version ${CARGO_DEB_VER}
+            if [[ "${OS_REL}" == "xenial" ]]; then
+              # Disable use of the default lzma feature which causes XZ compression to be used
+              # which then causes Lintian to fail with error:
+              #   E: krill: malformed-deb-archive newer compressed control.tar.xz
+              # Passing --fast to cargo-deb to disable use of XZ compression didn't help.
+              # See: https://github.com/kornelski/cargo-deb/issues/12
+              EXTRA_CARGO_INSTALL_ARGS="--no-default-features"
+            else
+              EXTRA_CARGO_INSTALL_ARGS=""
+            fi
+            cargo install cargo-deb --version ${CARGO_DEB_VER} --locked ${EXTRA_CARGO_INSTALL_ARGS}
             ;;
         esac
 
@@ -168,9 +178,7 @@ jobs:
       run: |
         case ${OS_NAME} in
           centos)
-            # Temporary workaround for https://github.com/cat-in-136/cargo-generate-rpm/issues/21
-            rustup toolchain install 1.52.0
-            cargo +1.52.0 install cargo-generate-rpm --version ${CARGO_GENERATE_RPM_VER} --locked
+            cargo install cargo-generate-rpm --version ${CARGO_GENERATE_RPM_VER} --locked
             ;;
         esac
 
@@ -253,20 +261,26 @@ jobs:
 
             # Select the correct systemd service unit file for the target operating system
             case ${MATRIX_IMAGE} in
-              ubuntu:xenial|centos:7)   SYSTEMD_SERVICE_UNIT_FILE="krill-ubuntu-xenial.krill.service"   ;;
-              ubuntu:bionic)            SYSTEMD_SERVICE_UNIT_FILE="krill-ubuntu-bionic.krill.service"   ;;
-              ubuntu:focal|centos:8)    SYSTEMD_SERVICE_UNIT_FILE="krill-ubuntu-focal.krill.service"    ;;
-              debian:stretch)           SYSTEMD_SERVICE_UNIT_FILE="krill-debian-stretch.krill.service"  ;;
-              debian:buster)            SYSTEMD_SERVICE_UNIT_FILE="krill-debian-buster.krill.service"   ;;
-              debian:bullseye)          SYSTEMD_SERVICE_UNIT_FILE="krill-debian-bullseye.krill.service" ;;
-              *) echo >&2 "ERROR: Unsupported matrix image value: '${MATRIX_IMAGE}'" ;;
+              centos:7)
+                SYSTEMD_SERVICE_UNIT_FILE="krill-ubuntu-xenial.krill.service"
+                # yum install fails on older CentOS with the default LZMA compression used by cargo generate-rpm since v0.5.0
+                # see: https://github.com/cat-in-136/cargo-generate-rpm/issues/30
+                EXTRA_CARGO_GENERATE_RPM_ARGS="--payload-compress gzip"
+                ;;
+              centos:8)
+                SYSTEMD_SERVICE_UNIT_FILE="krill-ubuntu-focal.krill.service"
+                EXTRA_CARGO_GENERATE_RPM_ARGS=""
+                ;;
+              *)
+                echo >&2 "ERROR: Unsupported matrix image value: '${MATRIX_IMAGE}'"
+                ;;
             esac
 
             # Copy the chosen systemd service unit file to where Cargo.toml expects it to be
             mkdir -p target/rpm
             cp pkg/common/${SYSTEMD_SERVICE_UNIT_FILE} target/rpm/krill.service
 
-            cargo generate-rpm
+            cargo generate-rpm ${EXTRA_CARGO_GENERATE_RPM_ARGS}
             ;;
         esac
 
