Run Lintian on produced .deb packages. (#292)
Run Lintian on produced .deb packages but inform only, do not fail the build.

diff --git a/.github/workflows/pkg.yml b/.github/workflows/pkg.yml
--- a/.github/workflows/pkg.yml
+++ b/.github/workflows/pkg.yml
@@ -97,9 +97,9 @@ jobs:
       env:
         DEBIAN_FRONTEND: noninteractive
 
-    - name: Install compilation dependencies
+    - name: Install compilation and other dependencies
       run: |
-          apt-get install -y build-essential jq libssl-dev pkg-config
+          apt-get install -y build-essential jq libssl-dev lintian pkg-config
       env:
         DEBIAN_FRONTEND: noninteractive
 
@@ -170,9 +170,16 @@ jobs:
           *)            echo 2>&1 "ERROR: Unexpected matrix image"; exit 1 ;;
         esac
         DEB_VER="${KRILL_VER}-1${OS_REL}"
-        cargo deb --variant $DEB_NAME --deb-version $DEB_VER
+        cargo deb --variant $DEB_NAME --deb-version $DEB_VER -v
       env:
         MATRIX_IMAGE: ${{ matrix.image }}
+
+    # See what Lintian thinks of our package but don't fail the build because of
+    # it. E.g. Cargo Deb doesn't compress man pages but Lintian (and Debian
+    # Policy) say they should be compressed.
+    - name: Verify the DEB package
+      run: |
+        lintian -v target/debian/*.deb || true
 
     # Upload the produced DEB package. The artifact will be available
     # via the GH Actions job summary and build log pages, but only to
