Try alternate way to get GitHub Actions user details.

diff --git a/.github/workflows/pkg.yml b/.github/workflows/pkg.yml
--- a/.github/workflows/pkg.yml
+++ b/.github/workflows/pkg.yml
@@ -129,15 +129,6 @@ jobs:
       run: |
         cargo install --git https://github.com/ximon18/cargo-deb.git --branch dh_installsystemd --rev $CARGO_DEB_VER cargo-deb
 
-    # Get GitHub user details needed to populate the minimal Debian package
-    # changelog below.
-    - uses: octokit/request-action@v2.x
-      id: get_user_details
-      with:
-        route: GET /user
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
     # Instruct cargo-deb to build the Debian package using the config section
     # in Cargo.toml for the specified "variant".
     - name: Create the DEB package
@@ -179,6 +170,12 @@ jobs:
           *)            echo 2>&1 "ERROR: Unexpected matrix image"; exit 1 ;;
         esac
 
+        case ${{ github.event_name }} in
+          pull_request) MAINTAINER="${{ github.event.pull_request.sender.name }} ${{ github.event.pull_request.sender.email }}" ;;
+          push)         MAINTAINER="${{ github.event.pusher.name }} ${{ github.event.pusher.email }}" ;;
+          *)            echo 2>&1 "ERROR: Unexpected GitHub Actions event"; exit 1 ;;
+        esac
+
         # Generate the changelog file that Debian packages are required to have.
         # See: https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#changelog
         echo "krill (${DEB_KRILL_VER}) unstable; urgency=medium" >debian/changelog
@@ -189,7 +186,6 @@ jobs:
         cargo deb --variant $DEB_NAME --deb-version $DEB_VER -v
       env:
         MATRIX_IMAGE: ${{ matrix.image }}
-        GH_USER_DETAILS: "${{ fromJson(steps.get_user_details.outputs.data).name }} <${{ fromJson(steps.get_user_details.outputs.data).email }}>"
 
     # See what Lintian thinks of our package but don't fail the build because of
     # it. E.g. Cargo Deb doesn't compress man pages but Lintian (and Debian
