Attempt to set unique legal package triples (name, ver, arch) per package when those packages are for different releases of the same distribution, i.e. Debian Stretch vs Debian Buster, as in the pkg repo the files for all distributions are stored in a single pool directory by their triple name and thus must be unique.

diff --git a/.github/workflows/pkg.yml b/.github/workflows/pkg.yml
--- a/.github/workflows/pkg.yml
+++ b/.github/workflows/pkg.yml
@@ -126,7 +126,30 @@ jobs:
     # in Cargo.toml for the specified "variant".
     - name: Create the DEB package
       run: |
-        cargo deb --variant $DEB_NAME
+        # Packages for different distributions (e.g. Stretch, Buster) of the same
+        # O/S (e.g. Debian) when served from a single package repository MUST have
+        # unique package_ver_architecture triples. Cargo deb can vary the name based
+        # on the 'variant' config section in use, but doesn't do so according to
+        # Debian policy (as it modifies the package name, not the package version).
+        #   Format: package_ver_architecture
+        #   Where ver has format: [epoch:]upstream_version[-debian_revision]
+        #   And debian_version should be of the form: 1<xxx>
+        #   Where it is common to set <xxx> to the O/S name.
+        # See:
+        #   - https://unix.stackexchange.com/a/190899
+        #   - https://www.debian.org/doc/debian-policy/ch-controlfields.html#version
+        # Therefore we generate the version ourselves.
+        KRILL_VER=$(cargo read-manifest | jq -r '.version')
+        case ${MATRIX_IMAGE} in
+          ubuntu:16.04) OS_REL=xenial ;;
+          ubuntu:18.04) OS_REL=bionic ;;
+          ubuntu:20.04) OS_REL=focal ;;
+          debian:9)     OS_REL=stretch ;;
+          debian:10)    OS_REL=buster ;;
+          *)            echo 2>&1 "ERROR: Unexpected matrix image"; exit 1 ;;
+        esac
+        DEB_VER="krill_${KRILL_VER}-1${OS_REL}_amd64"
+        cargo deb --variant $DEB_NAME --deb-version $DEB_VER
 
     # Upload the produced DEB package. The artifact will be available
     # via the GH Actions job summary and build log pages, but only to
